# Generated by Django 5.2.4 on 2025-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='method',
            field=models.CharField(blank=True, default='web', max_length=10, verbose_name='Método'),
        ),
    ]
