# Generated by Django 5.2.4 on 2025-07-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendance_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='method',
            field=models.CharField(blank=True, default='web', max_length=10),
        ),
    ]
